name: Build CV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: dusan-haustein-cv-eng.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: dusan-haustein-cv-eng
        path: dusan-haustein-cv-eng.pdf
        retention-days: 90
